### ISSUE TITLE
KeyboardDownRounded and ChevronRightRounded Deprecated

### ISSUE THREAD

**Issue by KhachDavid** [steviebaa/mui-nested-menu#1]
**Describe the bug**

These two icons used [here](https://github.com/steviebaa/mui-nested-menu/blob/main/src/NestedMenuItem.js#L10) and [here](https://github.com/steviebaa/mui-nested-menu/blob/main/src/NestedDropdown.js#L10) are deprecated. When I am trying to install this package, it keeps asking me to install these two dependencies. 

**Possible Solution**

Their names have been changed to KeyboardDownRoundedIcon and ChevronRightRoundedIcon. So, changing the import statements of these icons, would greatly help this library, as it is not running

**My OS**

I used two different intel-based Macbook laptops to test this. Both generated the same result, saying that these two icon dependencies don't exist

**Comment by steviebaa** [comment]
@KhachDavid I've updated the package to 2.0.0 as there was one small breaking change - changing the `data` prop to match the other components so it is now `menuItemsData` or something. 

Converted it all to typescript so it will be a lot more friendly for typescript users.

Gave the docs a bit of a freshen up. [mui-nested-menu.vercel.app](https://mui-nested-menu.vercel.app/)

Enjoy.
