### ISSUE TITLE
Would like property that is passed to callback

### ISSUE THREAD

**Issue by datumgeek** [steviebaa/mui-nested-menu#11]
I am trying to support a nested hierarchical menu (`<ContextMenu ...>...</ContextMenu>`) from right click on a set of tabs.  I am struggling to know which tab should receive the action from the menu in the callback call.

if a property was added to `ContextMenu` component and that property was passed to the callback when it was called, it would be very clean know which tab was clicked in the callback menu item...

**Comment by datumgeek** [comment]
Would like to create a PR, but not sure the steps to build and test locally...  tried `npm run build` and `npm run package:build` but neither produced what I see when i do `npm install mui-nested-menu`.

**Comment by steviebaa** [comment]
Hey @datumgeek,

To run it locally, you can just do `npm run start` and maybe add the `--watch` flag to make it easier. 

The `npm run pack` and those other commands are for npm publishing preparation. 

I'm not sure I completely understand the issue (maybe after some sleep 😆 ). Feel free to create a PR, I'll understand once I see that. 

I've just published 2.1.0 which gives more flexibility to the context menu so just make sure you pull recent changes on main. See issue #10 for more info on the change.

**Comment by steviebaa** [comment]
@datumgeek Just whipped up a quick PR to demo an idea that should help you out. Have a look at the file changes to get an idea of how it works.

https://github.com/steviebaa/mui-nested-menu/pull/15/files

**Comment by steviebaa** [comment]
Hmm yeah I suppose for that top level item it doesn't make sense. I make it required just to behave more like a "don't forget" prompt. If it were deeper nested in that context menu then it becomes useful.

I'd be inclined to just leave it as is for now unless it causes more issues down the track.
