### ISSUE TITLE
Can not access the same item in it's callback

### ISSUE THREAD

**Issue by YASHBRO** [steviebaa/mui-nested-menu#31]
I wanted to access some properties of my item in its callback for further use but it's not available as it's not been passed
Even the event object is not passed which we get with the `onClick` attribute

I solved this issue in PR #30 by passing the event and the item to the callback in that order i.e. `(event, item)`
I hope it's helpful

**Comment by steviebaa** [comment]
It is, you'll just need to be patient. I have other priorities and I'm on holiday at the moment.

**Comment by YASHBRO** [comment]
Ohh ok no problem
I have also initiated a Pull Request for the same and have also added those changes in Docs
Have a look whenever you are free
I have linked the PR with this issue
Thanks

**Comment by steviebaa** [comment]
published as [3.2.0](https://www.npmjs.com/package/mui-nested-menu/v/3.2.0)
