### ISSUE TITLE
Add a LICENSE file to project 

### ISSUE THREAD

**Issue by CherryBear-hub** [steviebaa/mui-nested-menu#4]
Add a LICENSE file to the project so that others wouldn't have issues using it.

**Comment by steviebaa** [comment]
Thanks @CherryBear-hub. I've added the MIT license to the project and the npm package (2.0.2)

Commit: https://github.com/steviebaa/mui-nested-menu/commit/a70e02ae6978146c21545cb87bb00c31fc69fca0
NPM: https://www.npmjs.com/package/mui-nested-menu/v/2.0.2
