### ISSUE TITLE
Allow passing props for the Menu component in NestedMenuItem

### ISSUE THREAD

**Issue by ARupertBMI** [steviebaa/mui-nested-menu#5]
Hi,

Would it be possible to allow the passing of props for the Menu component located in NestedMenuItem?  I'm trying to change the bgcolor of .MuiMenu-paper under the Menu component, but don't have a way to set the sx prop on the Menu

Thanks

**Comment by steviebaa** [comment]
Hey @ARupertBMI,

Good point, looks like the [interface has already allowed for it](https://github.com/steviebaa/mui-nested-menu/blob/main/src/mui-nested-menu/components/NestedMenuItem.tsx#L18), it just hasn't been passed along. 

Would you like to create a PR for it?

**Comment by ARupertBMI** [comment]
Sure I'll work on it.  Thanks!

**Comment by steviebaa** [comment]
Hey @ARupertBMI, just checking in to see if you were still keen to PR this one. I can probably do it tomorrow otherwise :)

**Comment by steviebaa** [comment]
Published to NPM as [2.0.4](https://www.npmjs.com/package/mui-nested-menu/v/2.0.4)
