### ISSUE TITLE
Any way to disable a IconMenuItem

### ISSUE THREAD

**Issue by wildcat-cs** [steviebaa/mui-nested-menu#6]
Hi.

Was looking at replacing the generic Menu Item with the IconMenuItem but it doesn't look like you can disable a menu option.  Am I missing something, or how hard do you think it would be to add this?

Thanks

**Comment by steviebaa** [comment]
Hey @wildcat-cs,

`IconMenuItem` just extends the MUI `MenuItem` component. There is a prop called `MenuItemProps` where you can access all the material ui `MenuItem` props.

This is the typical pattern you'll see in the packages seeing as the `IconMenuItem` is composed of a few elements. Does that help out?

```
<IconMenuItem
  leftIcon={<AdbIcon />}
  rightIcon={<FlutterDashIcon />}
  label={'Icon Menu Item'}
  onClick={handleClose}
  MenuItemProps={{disabled: true}}
/>
```
